[package]
name = "smhash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
rpassword = "7.0.0"
sha2 = "0.10.6"
hex = "0.4.3"